import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.experience': 'Experience',
    'nav.skills': 'Skills',
    'nav.education': 'Education',
    'nav.dashboard': 'Dashboard',
    'nav.predictor': 'ML Predictor',
    'nav.contact': 'Contact',

    // Hero Section
    'hero.welcome': 'Welcome to my portfolio',
    'hero.name': 'Alex Huang',
    'hero.subtitle': 'Data Engineer & Data Scientist with 6+ years of experience building scalable ETL pipelines, ML systems, and analytics platforms for Fortune 500 companies and innovative startups.',
    'hero.view_work': 'View My Work',
    'hero.download_resume': 'Download Resume',

    // Section Headers
    'section.professional_journey': 'PROFESSIONAL JOURNEY',
    'section.technical_expertise': 'TECHNICAL EXPERTISE',
    'section.academic_background': 'ACADEMIC BACKGROUND',
    'section.get_in_touch': 'GET IN TOUCH',

    // Experience Section
    'experience.title': 'Experience',
    'experience.location': 'Location',
    'experience.highlights': 'Key Achievements',
    'experience.role': 'Role',
    'experience.period': 'Period',
    'experience.company.real_messenger': 'Real Messenger',
    'experience.company.simo': 'SIMO',
    'experience.company.ames_it': 'Ames IT and Numeric Solutions',
    'experience.company.ucla_health': 'UCLA Health',
    'experience.company.warner_bros': 'Warner Bros',
    'experience.role.data_engineer': 'Data Engineer',
    'experience.role.data_analyst': 'Data Analyst',
    'experience.role.data_scientist': 'Data Scientist',
    'experience.role.bi_analyst': 'Business Intelligence Analyst II',
    'experience.role.business_analyst': 'Business Analyst',
    'experience.location.hong_kong': 'Hong Kong SAR',
    'experience.location.shenzhen': 'Shenzhen, China',
    'experience.location.los_angeles': 'Los Angeles, CA',
    'experience.highlight.real_messenger_1': 'Developed Airflow pipelines for ETL workflows with MongoDB and PostgreSQL',
    'experience.highlight.real_messenger_2': 'Built high-concurrency Go microservice handling 50K+ daily requests (<200ms)',
    'experience.highlight.real_messenger_3': 'Architected recommendation engine with Neural Collaborative Filtering and ANN search',
    'experience.highlight.real_messenger_4': 'Designed analytics API suite powering dashboards for 200K+ agents',
    'experience.highlight.simo_1': 'Designed ETL pipelines in AWS Databricks reducing manual reporting by 95%',
    'experience.highlight.simo_2': 'Developed interactive dashboards for telecom metrics visualization',
    'experience.highlight.simo_3': 'Implemented LSTM forecasting pipeline with 6.3% MAPE globally',
    'experience.highlight.simo_4': 'Packaged ML model as FastAPI service on AWS SageMaker',
    'experience.highlight.ames_it_1': 'Delivered training on end-to-end data science workflows and ML algorithms',
    'experience.highlight.ames_it_2': 'Taught SQL-based data engineering and model deployment with FastAPI',
    'experience.highlight.ames_it_3': 'Developed real-world case studies for fraud detection and credit scoring',
    'experience.highlight.ames_it_4': 'Guided students through supervised and unsupervised learning techniques',
    'experience.highlight.ucla_health_1': 'Analyzed patient readmission data, decreased readmission rate by 5%',
    'experience.highlight.ucla_health_2': 'Designed interactive dashboards for key metrics (Volume, Mortality, Length of Stay)',
    'experience.highlight.ucla_health_3': 'Built NLP models for text mining, improved sepsis classification accuracy by 12.6%',
    'experience.highlight.ucla_health_4': 'Developed ensemble learning models with 0.95 AUC for early sepsis prediction',
    'experience.highlight.warner_bros_1': 'Developed an automated end-to-end ETL pipeline using Databricks to migrate legacy CSV localization data into a centralized database',
    'experience.highlight.warner_bros_2': 'Designed and implemented a scalable star schema for localized talent metadata',
    'experience.highlight.warner_bros_3': 'Built interactive dashboards for localized talent data visualization and reporting',
    'experience.highlight.warner_bros_4': 'Developed XGBoost model in Python to forecast film box office, translating data insights into recommendations for movie release strategies',

    // Skills Section
    'skills.title': 'Skills',
    'skills.tools': 'Skills & Tools',
    'skills.programming': 'Programming',
    'skills.data_etl': 'Data & ETL',
    'skills.cloud_devops': 'Cloud & DevOps',
    'skills.ml_analytics': 'ML & Analytics',

    // Education Section
    'education.title': 'Education',
    'education.university': 'University of California, Los Angeles',
    'education.degree': 'Master of Science in Data Science',
    'education.period': '2021 - 2023',
    'education.gpa': 'GPA: 3.8/4.0',
    'education.rochester_degree': 'Master of Science in Business Analytics',
    'education.rochester_university': 'University of Rochester',
    'education.rochester_details': 'STEM-Certified Program | Meliora Scholarship Recipient',
    'education.rochester_period': 'December 2021',
    'education.usc_degree': 'Bachelor of Science in Business Administration',
    'education.usc_university': 'University of Southern California',
    'education.usc_details': 'Minor in Mathematical Finance',
    'education.usc_period': 'May 2019',

    // Contact Section
    'contact.title': 'Get In Touch',
    'contact.subtitle': "Let's Connect",
    'contact.description': 'I\'m always interested in hearing about new projects and opportunities. Feel free to reach out!',
    'contact.email': 'Email Me',
    'contact.resume': 'Download Resume',
    'contact.connect': 'Connect With Me',
    'contact.github': 'GitHub',
    'contact.linkedin': 'LinkedIn',
    'contact.location': '📍 Based in Hong Kong SAR | Authorized to work in HK with TTPS',
    'contact.phone': '📞 +852-6467-0968',
    'contact.terms': 'Terms',
    'contact.sitemap': 'Sitemap',

    // Skills List
    'skill.python': 'Python',
    'skill.sql': 'SQL',
    'skill.r': 'R',
    'skill.golang': 'Golang',
    'skill.javascript': 'JavaScript/TypeScript',
    'skill.apache_spark': 'Apache Spark',
    'skill.apache_hadoop': 'Apache Hadoop',
    'skill.airflow': 'Airflow',
    'skill.databricks': 'Databricks',
    'skill.postgresql': 'PostgreSQL',
    'skill.mongodb': 'MongoDB',
    'skill.mysql': 'MySQL',
    'skill.aws': 'AWS',
    'skill.kubernetes': 'Kubernetes',
    'skill.docker': 'Docker',
    'skill.git': 'Git',
    'skill.cicd': 'CI/CD',
    'skill.fastapi': 'FastAPI',
    'skill.tensorflow': 'TensorFlow',
    'skill.langchain': 'LangChain',
    'skill.tableau': 'Tableau',
    'skill.data_visualization': 'Data Visualization',
    'skill.certification_tableau': 'Tableau Desktop Specialist',
    'skill.certification_aws_practitioner': 'AWS Certified Cloud Practitioner',
    'skill.certification_aws_data_engineer': 'AWS Certified Data Engineer',
    'skill.tech_stack_title': 'Modern Tech Stack',
    'skill.tech_stack_description': 'Proficient in cutting-edge data engineering and ML technologies',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.view.performance': 'Performance Dashboard',
    'dashboard.view.healthcare': 'Healthcare Dashboard',
    'dashboard.performance.desc': 'Key metrics and achievements from my professional experience in data engineering and data science',
    'dashboard.healthcare.desc': 'Interactive healthcare operations dashboard built from the uploaded modified healthcare dataset with KPI cards, time series analysis, granularity controls, and multi-dimensional filters.',
    'dashboard.metric.daily_requests': 'Daily Requests Handled',
    'dashboard.metric.daily_requests_sub': 'Peak throughput achieved',
    'dashboard.metric.model_accuracy': 'Model Accuracy',
    'dashboard.metric.model_accuracy_sub': 'AUC score for sepsis prediction',
    'dashboard.metric.response_time': 'Response Time',
    'dashboard.metric.response_time_sub': 'Average API latency',
    'dashboard.metric.data_sources': 'Data Sources',
    'dashboard.metric.data_sources_sub': 'Integrated databases & APIs',
    'dashboard.metric.team_size': 'Team Size',
    'dashboard.metric.team_size_sub': 'Agents served by analytics',
    'dashboard.metric.cost_reduction': 'Cost Reduction',
    'dashboard.metric.cost_reduction_sub': 'Monthly savings achieved',
    'dashboard.kpi.patient_volume': 'Patient Volume',
    'dashboard.kpi.total_billing': 'Total Billing',
    'dashboard.kpi.avg_stay': 'Avg Length of Stay',
    'dashboard.kpi.doctor_volume': 'Doctor Volume',
    'dashboard.kpi.total_hospitals': 'Total Hospitals',
    'dashboard.chart.patient_transaction': 'Patient Volume & Transaction Amount',
    'dashboard.chart.patient_transaction.desc': 'Patient count on the left axis, billing amount on the right axis, grouped by date of admission.',
    'dashboard.chart.length_stay': 'Length of Stay Over Time',
    'dashboard.chart.length_stay.desc': 'Average length of stay by date of admission.',
    'dashboard.filters.title': 'Parameters & Filters',
    'dashboard.filters.desc': 'Granularity, date range, and healthcare filters.',
    'dashboard.filters.granularity': 'Date Granularity',
    'dashboard.filters.date_from': 'Date From',
    'dashboard.filters.date_to': 'Date To',
    'dashboard.filters.age_min': 'Age Min',
    'dashboard.filters.age_max': 'Age Max',
    'dashboard.filters.hospital': 'Hospital',
    'dashboard.filters.admission_type': 'Admission Type',
    'dashboard.filters.gender': 'Gender',
    'dashboard.filters.insurance': 'Insurance Provider',
    'dashboard.filters.medication': 'Medication',
    'dashboard.filters.test_results': 'Test Results',
    'dashboard.filters.all': 'All',
    'dashboard.chart.patient_volume': 'Patient Volume',
    'dashboard.chart.transaction_amount': 'Transaction Amount',
    'dashboard.chart.length_of_stay': 'Length of Stay',
    'dashboard.chart.y_axis.patient': 'Patient Count',
    'dashboard.chart.y_axis.transaction': 'Transaction (M)',
    'dashboard.chart.y_axis.stay': 'Avg Length of Stay',
    'dashboard.chart.days': 'days',
    'dashboard.granularity.daily': 'Daily',
    'dashboard.granularity.weekly': 'Weekly',
    'dashboard.granularity.monthly': 'Monthly',
    'dashboard.granularity.quarterly': 'Quarterly',
    'dashboard.granularity.yearly': 'Yearly',

    // Salary Predictor
    'predictor.title': 'ML Salary Predictor',
    'predictor.description': 'Predict salaries based on experience, education, and skills using machine learning models.',
    'predictor.submit': 'Predict Salary',
    'predictor.occupation': 'Occupation',
    'predictor.age': 'Age',
    'predictor.gender': 'Gender',
    'predictor.education': 'Education',
    'predictor.years_of_experience': 'Years of Experience',
    'predictor.current_salary': 'Current Salary',
    'predictor.required_fields': 'Please fill in all required fields',
    'predictor.prediction_failed': 'Prediction failed. Please try again.',
    'predictor.predicting': 'Predicting...',
    'predictor.results': 'Prediction Results',
    'predictor.predicted_salary': 'Predicted Salary (10 years)',
    'predictor.confidence_score': 'Confidence Score',
    'predictor.salary_growth': 'Salary Growth',
    'predictor.growth_percentage': 'Growth Percentage',
    'predictor.predict_now': 'Predict Now',
    'predictor.high_school': 'High School',
    'predictor.bachelor': 'Bachelor',
    'predictor.master': 'Master',
    'predictor.phd': 'PhD',
    'predictor.male': 'Male',
    'predictor.female': 'Female',
    'predictor.other': 'Other',
    'predictor.header.subtitle': 'Predict your potential salary growth over the next 10 years using machine learning. Input your professional details and get personalized insights.',
    'predictor.header.machine_learning': 'MACHINE LEARNING',
    'predictor.header.title': '10-Year Salary Predictor',
    'predictor.form.title': 'Your Profile',
    'predictor.form.occupation_placeholder': 'Select your occupation',
    'predictor.form.age_placeholder': 'Enter your age',
    'predictor.form.gender_placeholder': 'Select your gender',
    'predictor.form.education_placeholder': 'Select education level',
    'predictor.form.experience_placeholder': 'Enter years (0-60)',
    'predictor.form.salary_placeholder': 'Enter your current salary',
    'predictor.form.predict_button': 'Predict Salary',
    'predictor.form.predicting_button': 'Predicting...',
    'predictor.results.predicted_10_years': 'Predicted Salary in 10 Years',
    'predictor.results.confidence': 'Prediction Confidence',
    'predictor.results.confidence_percent': 'Confidence',
    'predictor.results.insights': 'Key Insights',
    'predictor.results.insight1': 'Your predicted salary growth is',
    'predictor.results.insight2': 'This represents a',
    'predictor.results.insight3': 'The prediction is based on occupation, experience, education, and current compensation',
    'predictor.results.placeholder': 'Fill in your profile and click "Predict Salary" to see your 10-year salary projection',
    'predictor.occupation.software_engineer': 'Software Engineer',
    'predictor.occupation.data_scientist': 'Data Scientist',
    'predictor.occupation.product_manager': 'Product Manager',
    'predictor.occupation.designer': 'Designer',
    'predictor.occupation.data_engineer': 'Data Engineer',
    'predictor.occupation.devops_engineer': 'DevOps Engineer',
    'predictor.occupation.business_analyst': 'Business Analyst',
    'predictor.occupation.project_manager': 'Project Manager',
    'predictor.occupation.consultant': 'Consultant',
    'predictor.occupation.other': 'Other',

    // Loading/Error
    'loading': 'Loading...',
    'loading.healthcare': 'Loading healthcare data...',
    'loading.dashboard': 'Loading dashboard code and optimized healthcare dataset.',
    'error.retry': 'Retry',
    'error.failed': 'Failed to load data. Please try again.',

    // Footer
    'footer.copyright': '© 2026 Alex Huang. All rights reserved.',
    'footer.back': 'Back to Portfolio',
    'footer.privacy': 'Privacy',
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.experience': '经历',
    'nav.skills': '技能',
    'nav.education': '教育',
    'nav.dashboard': '仪表板',
    'nav.predictor': '薪资预测',
    'nav.contact': '联系',

    // Hero Section
    'hero.welcome': '欢迎来到我的作品集',
    'hero.name': '黄兴奇',
    'hero.subtitle': '拥有6+年经验的数据工程师与数据科学家，曾为财富500强企业和创新初创公司构建可扩展的ETL管道、机器学习系统和分析平台。',
    'hero.view_work': '查看我的作品',
    'hero.download_resume': '下载简历',

    // Section Headers
    'section.professional_journey': '职业历程',
    'section.technical_expertise': '技术专长',
    'section.academic_background': '学术背景',
    'section.get_in_touch': '联系我',

    // Experience Section
    'experience.title': '经历',
    'experience.location': '地点',
    'experience.highlights': '主要成就',
    'experience.role': '职位',
    'experience.period': '时期',
    'experience.company.real_messenger': 'Real Messenger',
    'experience.company.simo': 'SIMO',
    'experience.company.ames_it': 'Ames IT and Numeric Solutions',
    'experience.company.ucla_health': 'UCLA Health',
    'experience.company.warner_bros': 'Warner Bros',
    'experience.role.data_engineer': '数据工程师',
    'experience.role.data_analyst': '数据分析师',
    'experience.role.data_scientist': '数据科学家',
    'experience.role.bi_analyst': '商业智能分析师',
    'experience.role.business_analyst': '业务分析师',
    'experience.location.hong_kong': '香港特别行政区',
    'experience.location.shenzhen': '中国深圳',
    'experience.location.los_angeles': '美国洛杉矶',
    'experience.highlight.real_messenger_1': '开发了使用MongoDB和PostgreSQL的ETL工作流程的Airflow管道',
    'experience.highlight.real_messenger_2': '构建了高并发Go微服务，每日处理5万+请求（<200ms）',
    'experience.highlight.real_messenger_3': '使用神经协同过滤和ANN搜索架构了推荐引擎',
    'experience.highlight.real_messenger_4': '设计了为20万+代理提供仪表板支持的分析API套件',
    'experience.highlight.simo_1': '在AWS Databricks中设计ETL管道，减少95%的手动报告',
    'experience.highlight.simo_2': '开发了用于电信指标可视化的交互式仪表板',
    'experience.highlight.simo_3': '实施了具有全球6.3% MAPE的LSTM预测管道',
    'experience.highlight.simo_4': '将ML模型打包为AWS SageMaker上的FastAPI服务',
    'experience.highlight.ames_it_1': '提供端到端数据科学工作流程和ML算法的培训',
    'experience.highlight.ames_it_2': '教授基于SQL的数据工程和使用FastAPI的模型部署',
    'experience.highlight.ames_it_3': '开发了用于欺诈检测和信用评分的现实案例研究',
    'experience.highlight.ames_it_4': '指导学生通过监督和无监督学习技术',
    'experience.highlight.ucla_health_1': '分析患者再入院数据，再入院率降低5%',
    'experience.highlight.ucla_health_2': '为关键指标（量、死亡率、住院时长）设计交互式仪表板',
    'experience.highlight.ucla_health_3': '构建用于文本挖掘的NLP模型，脓毒症分类准确率提高12.6%',
    'experience.highlight.ucla_health_4': '开发了具有0.95 AUC的集成学习模型用于早期脓毒症预测',
    'experience.highlight.warner_bros_1': '使用Databricks开发自动化端到端ETL管道，将遗留CSV本地化数据迁移到集中式数据库',
    'experience.highlight.warner_bros_2': '设计并实施了可扩展的星型模式用于本地化人才元数据',
    'experience.highlight.warner_bros_3': '构建了用于本地化人才数据可视化和报告的交互式仪表板',
    'experience.highlight.warner_bros_4': '在Python中开发XGBoost模型预测电影票房，将数据洞察转化为电影发布策略建议',

    // Skills Section
    'skills.title': '技能',
    'skills.tools': '技能与工具',
    'skills.programming': '编程语言',
    'skills.data_etl': '数据与ETL',
    'skills.cloud_devops': '云计算与DevOps',
    'skills.ml_analytics': '机器学习与分析',

    // Education Section
    'education.title': '教育',
    'education.university': '加利福尼亚大学洛杉矶分校',
    'education.degree': '数据科学硕士',
    'education.period': '2021 - 2023',
    'education.gpa': 'GPA: 3.8/4.0',
    'education.rochester_degree': '商业分析科学硕士',
    'education.rochester_university': '罗切斯特大学',
    'education.rochester_details': 'STEM认证项目 | Meliora奖学金获得者',
    'education.rochester_period': '2021年12月',
    'education.usc_degree': '工商管理学士',
    'education.usc_university': '南加州大学',
    'education.usc_details': '数学金融辅修',
    'education.usc_period': '2019年5月',

    // Contact Section
    'contact.title': '联系我',
    'contact.subtitle': '让我们联系',
    'contact.description': '我总是对听到新项目和机会感兴趣。欢迎随时联系我！',
    'contact.email': '发送邮件',
    'contact.resume': '下载简历',
    'contact.connect': '与我联系',
    'contact.github': 'GitHub',
    'contact.linkedin': 'LinkedIn',
    'contact.location': '📍 基于深圳',
    'contact.phone': '📞 +86-152-0755-3658',
    'contact.terms': '条款',
    'contact.sitemap': '网站地图',

    // Skills List
    'skill.python': 'Python',
    'skill.sql': 'SQL',
    'skill.r': 'R',
    'skill.golang': 'Golang',
    'skill.javascript': 'JavaScript/TypeScript',
    'skill.apache_spark': 'Apache Spark',
    'skill.apache_hadoop': 'Apache Hadoop',
    'skill.airflow': 'Airflow',
    'skill.databricks': 'Databricks',
    'skill.postgresql': 'PostgreSQL',
    'skill.mongodb': 'MongoDB',
    'skill.mysql': 'MySQL',
    'skill.aws': 'AWS',
    'skill.kubernetes': 'Kubernetes',
    'skill.docker': 'Docker',
    'skill.git': 'Git',
    'skill.cicd': 'CI/CD',
    'skill.fastapi': 'FastAPI',
    'skill.tensorflow': 'TensorFlow',
    'skill.langchain': 'LangChain',
    'skill.tableau': 'Tableau',
    'skill.data_visualization': '数据可视化',
    'skill.certification_tableau': 'Tableau桌面专家',
    'skill.certification_aws_practitioner': 'AWS认证云从业者',
    'skill.certification_aws_data_engineer': 'AWS认证数据工程师',
    'skill.tech_stack_title': '现代技术栈',
    'skill.tech_stack_description': '精通尖端数据工程和ML技术',

    // Dashboard
    'dashboard.title': '仪表板',
    'dashboard.view.performance': '绩效仪表板',
    'dashboard.view.healthcare': '医疗保健仪表板',
    'dashboard.performance.desc': '我在数据工程和数据科学专业经验中的关键指标和成就',
    'dashboard.healthcare.desc': '基于上传的医疗数据集构建的交互式医疗运营仪表板，包含KPI卡片、时间序列分析、粒度控制和多维度筛选。',
    'dashboard.metric.daily_requests': '每日处理请求数',
    'dashboard.metric.daily_requests_sub': '达到的峰值吞吐量',
    'dashboard.metric.model_accuracy': '模型准确率',
    'dashboard.metric.model_accuracy_sub': '脓毒症预测的AUC得分',
    'dashboard.metric.response_time': '响应时间',
    'dashboard.metric.response_time_sub': '平均API延迟',
    'dashboard.metric.data_sources': '数据源',
    'dashboard.metric.data_sources_sub': '集成的数据库和API',
    'dashboard.metric.team_size': '团队规模',
    'dashboard.metric.team_size_sub': '分析服务覆盖的代理数量',
    'dashboard.metric.cost_reduction': '成本降低',
    'dashboard.metric.cost_reduction_sub': '实现的月度节省',
    'dashboard.kpi.patient_volume': '患者量',
    'dashboard.kpi.total_billing': '总账单',
    'dashboard.kpi.avg_stay': '平均住院天数',
    'dashboard.kpi.doctor_volume': '医生数量',
    'dashboard.kpi.total_hospitals': '医院总数',
    'dashboard.chart.patient_transaction': '患者量与交易金额',
    'dashboard.chart.patient_transaction.desc': '左轴显示患者数量，右轴显示账单金额，按入院日期分组。',
    'dashboard.chart.length_stay': '住院时长趋势',
    'dashboard.chart.length_stay.desc': '按入院日期显示的平均住院天数。',
    'dashboard.filters.title': '参数与筛选',
    'dashboard.filters.desc': '粒度、日期范围和医疗保健筛选。',
    'dashboard.filters.granularity': '日期粒度',
    'dashboard.filters.date_from': '起始日期',
    'dashboard.filters.date_to': '结束日期',
    'dashboard.filters.age_min': '最小年龄',
    'dashboard.filters.age_max': '最大年龄',
    'dashboard.filters.hospital': '医院',
    'dashboard.filters.admission_type': '入院类型',
    'dashboard.filters.gender': '性别',
    'dashboard.filters.insurance': '保险公司',
    'dashboard.filters.medication': '药物',
    'dashboard.filters.test_results': '测试结果',
    'dashboard.filters.all': '全部',
    'dashboard.chart.patient_volume': '患者量',
    'dashboard.chart.transaction_amount': '交易金额',
    'dashboard.chart.length_of_stay': '住院时长',
    'dashboard.chart.y_axis.patient': '患者数量',
    'dashboard.chart.y_axis.transaction': '交易（百万）',
    'dashboard.chart.y_axis.stay': '平均住院天数',
    'dashboard.chart.days': '天',
    'dashboard.granularity.daily': '每日',
    'dashboard.granularity.weekly': '每周',
    'dashboard.granularity.monthly': '每月',
    'dashboard.granularity.quarterly': '每季度',
    'dashboard.granularity.yearly': '每年',

    // Salary Predictor
    'predictor.title': '机器学习薪资预测',
    'predictor.description': '使用机器学习模型根据经验、教育和技能预测薪资。',
    'predictor.submit': '预测薪资',
    'predictor.occupation': '职业',
    'predictor.age': '年龄',
    'predictor.gender': '性别',
    'predictor.education': '教育',
    'predictor.years_of_experience': '工作经验年限',
    'predictor.current_salary': '当前年薪',
    'predictor.required_fields': '请填写所有必填字段',
    'predictor.prediction_failed': '预测失败，请重试。',
    'predictor.predicting': '预测中...',
    'predictor.results': '预测结果',
    'predictor.predicted_salary': '预测薪资（10年）',
    'predictor.confidence_score': '置信度',
    'predictor.salary_growth': '薪资增长',
    'predictor.growth_percentage': '增长率',
    'predictor.predict_now': '立即预测',
    'predictor.high_school': '高中',
    'predictor.bachelor': '本科',
    'predictor.master': '硕士',
    'predictor.phd': '博士',
    'predictor.male': '男',
    'predictor.female': '女',
    'predictor.other': '其他',
    'predictor.header.subtitle': '使用机器学习预测您未来10年的潜在薪资增长。输入您的职业详细信息，获得个性化见解。',
    'predictor.header.machine_learning': '机器学习',
    'predictor.header.title': '10年薪资预测器',
    'predictor.form.title': '您的档案',
    'predictor.form.occupation_placeholder': '选择您的职业',
    'predictor.form.age_placeholder': '输入您的年龄',
    'predictor.form.gender_placeholder': '选择您的性别',
    'predictor.form.education_placeholder': '选择教育水平',
    'predictor.form.experience_placeholder': '输入年限（0-60）',
    'predictor.form.salary_placeholder': '输入您当前的薪资',
    'predictor.form.predict_button': '预测薪资',
    'predictor.form.predicting_button': '预测中...',
    'predictor.results.predicted_10_years': '10年后预测薪资',
    'predictor.results.confidence': '预测置信度',
    'predictor.results.confidence_percent': '置信度',
    'predictor.results.insights': '关键见解',
    'predictor.results.insight1': '您的预测薪资增长10年内将达到',
    'predictor.results.insight2': '这代表比您当前薪资增长',
    'predictor.results.insight3': '该预测基于职业、经验、教育和当前薪酬',
    'predictor.results.placeholder': '填写您的档案并点击"预测薪资"查看您的10年薪资预测',
    'predictor.occupation.software_engineer': '软件工程师',
    'predictor.occupation.data_scientist': '数据科学家',
    'predictor.occupation.product_manager': '产品经理',
    'predictor.occupation.designer': '设计师',
    'predictor.occupation.data_engineer': '数据工程师',
    'predictor.occupation.devops_engineer': 'DevOps工程师',
    'predictor.occupation.business_analyst': '业务分析师',
    'predictor.occupation.project_manager': '项目经理',
    'predictor.occupation.consultant': '顾问',
    'predictor.occupation.other': '其他',

    // Loading/Error
    'loading': '加载中...',
    'loading.healthcare': '加载医疗数据中...',
    'loading.dashboard': '加载仪表板代码和优化的医疗数据集。',
    'error.retry': '重试',
    'error.failed': '加载数据失败，请重试。',

    // Footer
    'footer.copyright': '© 2026 黄兴奇。保留所有权利。',
    'footer.back': '返回作品集',
    'footer.privacy': '隐私',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    // Get language from localStorage or default to 'en'
    const saved = localStorage.getItem('language') as Language;
    return saved && (saved === 'en' || saved === 'zh') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}